# EEGNet + EA + global MMD | seed 2027

model: EEGNet
dataset: THU

overrides:
  is_training: true
  exp_tag: eegnet_all_sub1_20_k32_bgds4_ea_globalmmd_seed2027

  source_selection: All
  all_source_batch_policy: random_k
  all_source_sampling_mode: uniform

  held_out_start_id: 1
  held_out_end_id: 20

  subject_batch_size: 64
  subjects_per_batch: 32

  learning_rate: 0.001
  random_seed: 2027
  epochs: 400
  early_stop_start_epoch: 30
  patience: 10

  ea_enable: true
  ea_cov_eps: 1.0e-6

  source_train_bg_downsample_enable: true
  source_train_bg_downsample_bg_to_pos_ratio: 4.0
  source_train_bg_downsample_seed: 2027

  use_target_stream: true
  lambda_align: 0.1
  alignment_loss: global_mmd

  val_batch_size: 1024
  minimal_log: true
  debug_domain_batch: false
  log_runtime: false

  deterministic_run: true
  cudnn_benchmark: false
  matmul_precision: highest
